### ISSUE TITLE
Stop requiring a specific command

### ISSUE THREAD

**Issue by mhsmith** [j0057/setuptools-version-command#9]
Version 1.x allowed you to use any command you want, but version 2.x requires it to be "git describe [--long]". This unnecessarily limits the usefulness of the module. What if you want to use other parameters to git describe, or you use another source control system, or  you have your own custom version number script?

Adding for Google: "Unsupported SCM command"

**Comment by j0057** [comment]
Hey, when I wrote the limitation I thought you wouldn't want to run just anything, so that's why it's there. I thought that other VCS'es could be whitelisted. But since it's python code, nothing is stopping the author from just doing whatever they please, so I agree the limitation could be taken out.

**Comment by j0057** [comment]
I uploaded version 2.1a0 to PyPI, it should work for you.

**Comment by mhsmith** [comment]
Thanks!
